### ISSUE TITLE
genesyscloud_tf_export

### ISSUE THREAD

**Issue by saravanakumar80** [MyPureCloud/terraform-provider-genesyscloud#126]
i am trying to use export without specifying the resource type  the plugin was crashed
i am getting below error. 

due to this the demo on Cx as Code was failed today for us. 

![image](https://user-images.githubusercontent.com/72588594/137345458-6506707f-c365-4312-aa67-2aabec0027c0.png)

**Comment by ronanwatkins** [comment]
Hi, sorry you experienced that crash during a demo.
We accessed the `rrule` property of an architect schedule without checking if it was nil.
We assumed it was set because the swagger documentation has it marked as required, some times the swagger documentation is not consistent with the API responses.

I've created a PR to fix this.
