### ISSUE TITLE
--forceUnlock command line parameter

### ISSUE THREAD

**Issue by asadsaqlain** [MyPureCloud/terraform-provider-genesyscloud#316]
Hi,

While publishing a new version (through terraform cloud) I'm getting following error. I know I can use --forceUnlock in archy (windows cli) in different ways but what should I do to resolve this in terraform (cloud) or how can i add a config file? Everytime I need to unlock flow in Architect before I publish with terraform cloud.

type: 'inboundcall' ) is locked by another entity. You can use the --forceUnlock command line parameter if you wish to publish flows locked by another entity.

Cheers, Asad

**Comment by carnellj-genesys** [comment]
Hi,

Is someone else modifying the flow that you are trying to deploy.  That seems to be counter to an immutable CI/CD pipeline.  Usually, I recommend people do all of their flow development in a dev environment and then export the flow.  Then they use Terraform to deploy the flow and dependent objects and then do not allow anyone to modify the flow in the target environments except through deploys in Terraform.

Can you give me a little more background on what you are doing in your environment?

Thanks,
     John

**Comment by asadsaqlain** [comment]
Hi John,

THanks for you reply.

There are some situations where someone changes a flow in architect itself and leaves it locked. And I can understand that it's against the ci/cd pipelines construction. But we need to have a mechanisim, like in archy windows cli where we can add a config file with --forceUnlock command line parameter. So my question is, is there a way we can add such parameter through terraform cloud or do we need to take some workaround path like using a python script to resolve this?

KR, Asad

**Comment by carnellj-genesys** [comment]
Hi Asad,

I can understand that :).  Beatings will continue until architect flows are only managed through our CI/CD pipeline.

I can chat with our Architect team about whether they want to add this as a feature.  Even if they do want to do this, it involves making changes to our service that deploys flows on behalf of our terraform service.  This could take some time to go through a prioritization/development cycle.

You have a couple of choices here:

1.  You could write a python script to unlock the script to force unlock the file

2.  Alternatively, install archy CLI in your deployment pipeline and then use the archy CLI to do the deployment.  We put the architect flow resource in terraform out there to simplify deployments, but for customers who need more control over their flow deployments, it is extremely simple to install Archy in your CI/CD pipeline and then use the archy CLI with whatever command parameters you want to pass it.  

In terraform, you could use a local-exec command to call out to Archy to do the deployment.  Since the archy CLI does not participate in Terraform's dependency graph you would need to a depends_on in your resource definitions to ensure that the flows got deployed in the right order.

Hope that helps.

Thanks,
     John

**Comment by asadsaqlain** [comment]
Hi John,

THanks again for a comprehensive answer, I really appriciate it.

I think I would rather go for the first option (even here need to do some research work :)). But second option also not seems be possible with terraform cloud even though that would be much simpler.

THanks, Asad
