### ISSUE TITLE
genesyscloud_architect_datatable

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#402]
**Team -
If we need to add new properties to the existing data table then we are seeing the full data table getting deleted and creating a new table in this Version 1.9.0**  Hence DB ID of the data table breaks in other configurations. 

In the earlier version if we add new properties to the existing data table the DB id remains the same. 

Please have this corrected as before

![image](https://user-images.githubusercontent.com/92093419/206272672-6d5e54a4-3bf8-44ac-a45f-a78e2628d270.png)

![image](https://user-images.githubusercontent.com/92093419/206272737-35f7cd25-cff2-4afa-b37f-5aea6a2416c9.png)

**Comment by carnellj-genesys** [comment]
Hi guys,

I think I understand what happened here.  Back in release notes 1.5, the ForceNew was added to the architect_datatables resource because the datatables API will return an error if there are records present in a table and you try to modify the data tables property by changing its type or deleting it. 

The developer added the ForceNew attribute thinking in these situations you could just drop and recreate the table, not realizing that there was linkage in the architect flow.  I am going to revert ForceNew out of the resource and I am hoping to have it released sometime next week.

The implication of this is that if you are going to modify your data tables by removing a property or updating its type, you will need to remove the data table from the terraform state (e.g. terraform state rm <<resourcetype.resourcename>>) manually delete the data table records and then re-run your Terraform deploy with the new definitions.

The behavior is to what you see in a relational database table.  You can add columns, but you cant remove or delete a column if there is data present in the table.

Sorry for the inconvenience.  You can drop back to the old version of the provider to work around this until we get a new fix out.

Thanks,
    John Carnell
    Manager, Developer Engagement
