### ISSUE TITLE
The prioritized list of media regions through which media can stream.

### ISSUE THREAD

**Issue by asadsaqlain** [MyPureCloud/terraform-provider-genesyscloud#410]
Hi,

Tried different ways but seems like you can't add/manage media regions from CX as Code. Also if you manage sites from CX as Code, manually added prioritized list of regions will be overwritten with next run. So, is there a way to add/manage those regions from CX as Code?

Thanks, Asad

**Comment by carnellj-genesys** [comment]
Hi Asad,

If you are trying to add regions to a site via CX as Code, CX as Code expects to be the "keeper" of the region info.  As a result, when you then add things manually via the UI, CLI, or API you will run into issues as Terraform (the underlying code for CX as Code) you will run into issues.   Is the issue that you can not add media regions to the site?  Generally, media regions are pre-defined so you just need to reference them.

If you do add a media region to your site manually, then you need to make sure you import the site back into Terraform or update the site in CX as Code definitions before your next deploy using Terraform. 

Most of the company is on holiday break until Jan 3rd, but if you have further questions, you might want to post on the developer forum (developer.genesys.cloud/forum) as we have more eyes on the forum.

Regardless I will check in on this issue Tuesday morning.

Thanks,
    John Carnell
    Manager, Developer Engagement

**Comment by asadsaqlain** [comment]
Hi John,

Thanks for your detailed answer. 

But, I forgot to mention that I also had created sites manually and set the media regions preference there. But when I import/export from Cloud back in Terraform media regions preference is not available in the config. So I assume, as I also can't find any info about media regions in Terraform resource documentation, that it was never developed/introduced in the code. Only what you can introduce in the config is "media_regions_use_latency_based = true/false". 

Please check: https://registry.terraform.io/providers/MyPureCloud/genesyscloud/latest/docs/resources/telephony_providers_edges_site

Hence I think it can be developed in coming releases. But don't know how to ask for this idea. Can you/someone help with this?

Thanks and wish you a happy new year in advance :)..

Cheers, Asad

**Comment by carnellj-genesys** [comment]
Hi Asad,

Thanks for the additional information.  When we build our CX as Code components we always go off our public API definitions.  When you pointed me to the UI I looked at the HTTP PUT and the body with the mediaRegions attribute being set.  I worked my way back through our API gateway layer and discovered that the engineering team had marked the mediaRegions field as internal which means it does not show up in our SDK or documentation.

It turns out the engineering team that owns the API had forgotten to mark the field for external consumption.  So I am going to open a ticket on this.  I can not get an ETA quite yet on when it will get added to CX as Code.  I have to get the fix in on the public API layer first and once that is merged and deployed, our SDK code generation process will add the field to the SDK, and then it will get added to the CX as Code provider.  My best guess is 2-3 weeks out.  I would keep an eye on the release notes.  It will be the next thing I work on, but it has multiple pieces that need to be reviewed and then merged before I can make the CX as Code changes.

**Comment by asadsaqlain** [comment]
Thanks John to pick this up!

**Comment by carnellj-genesys** [comment]
Hi Asad,

I have added media regions to the site object.  https://github.com/MyPureCloud/terraform-provider-genesyscloud/releases/tag/v1.12.0

**Comment by asadsaqlain** [comment]
Hi John,

Thanks a lot for the effort and confirming back.

Cheers
