### ISSUE TITLE
genesyscloud_group- Include Owners

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#510]
Group -  
For Groups in Genesys Console GUI, we have one option called " Include Owners "
![image](https://user-images.githubusercontent.com/92093419/235913132-f40b7543-327a-4b23-9686-d2a62b5b4d26.png)

How this can be unchecked using Cx-As-Code or an API please have this included if not available.

thanks

**Comment by carnellj-genesys** [comment]
Hi Saravana,

Thanks for reaching out to us.  I am not sure yet as this appears to be new.  I will ping Jeremy Gillip once I have a better idea of what this is.

Thanks,
    John

**Comment by carnellj-genesys** [comment]
Hi Sarvana,

The field in question is not part of the groups API.  It is actually is a private API that was never exposed in our public API hence it does not show up in our docs.   I have pinged the dev team to ask why the API is unpublished.

**Comment by saravanakumar-rogers** [comment]
Hi Do we have any update on the API ? in New release 1.17.0 is fixed?

**Comment by carnellj-genesys** [comment]
No update.  This is not fixed in v.17

**Comment by carnellj-genesys** [comment]
Hi Saravankumar,

I met with the API team.  It turns out the old API that is being used is an extremely old and was purposely kept visible because there were plans to replace it.  (The API in question is /api/v2/groups/{Pgfgdf}/profile and is not even marked available in our API explorer).  

The API owners are in the process of migrating most of the API over to a more robust and "visible" call (e.g. the groups API). 
but not yet moved this functionality. I am going to get a ticket for this on their backlog, but I do not have an ETA on when they are going to begin this work.  Once they have completed their work, this should be relatively straightforward to add to the groups API.

Thanks,
     John Carnell

I am going to close this comment, but keep our internal Dev tickets so it can be tracked.
